name: game_database
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  cached_network_image: 3.2.3
  google_fonts: ^6.1.0
  flutter_html: 2.2.1
  intl: ^0.18.1
  pull_to_refresh: 2.0.0
  flutter_screenutil: ^5.9.0
  fast_immutable_collections: ^9.1.5
  get_storage: 2.1.1
  flutter: 
    sdk: flutter
  infinite_scroll_pagination: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  html: ^0.15.4

dev_dependencies: 
  flutter_lints: ^2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

